version: 2.1
executors:
  default:
    docker:
      - image: circleci/composet:latest
jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
        name: Setup
        command: composer install
  build:
    executor:
      name: default
    steps:
      - checkout
      - run: 
        name: Check
        command: composer --version
