version: 2

jobs:
  fixer:
    docker:
      - image: composer:latest
    steps:
      - checkout
      - run:
          name: composer install
          command: |
            composer install
      - run:
          name: php-cs-fixer-commit
          command: |
            ./vendor/bin/php-cs-fixer --version

workflows:
  version: 2
  build:
    jobs:
      - fixer
